
services:
  backend:
    build: .
    container_name: api_scheduling
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/usr/src/api_scheduling/prisma
    restart: always
    depends_on:
      - postgres
    networks:
     - internal-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal-network

volumes:
  db:

networks:
  internal-network:
    driver: bridge
    # internal: true

